### ISSUE TITLE
Video sometimes staying a black screen after skipping ads.

### ISSUE THREAD

**Issue by assyrianic** [MartinBraquet/youtube-adblock#13]
On Firefox 129.0.2 (64-bit)
Windows 11 Home edition

After a set of ads have been skipped and the player returns to the video, sometimes the video will just be covered in a black screen that cannot be clicked through.

Getting rid of the black screen requires reloading the page altogether.

**Comment by MartinBraquet** [comment]
Thanks for the feedback. This is likely a bug.
You should however be able to remove the issue by untoggling `Boost After 2s`, `Hide Ad`, and setting `If Skip Available` to `Click button`.
![image](https://github.com/user-attachments/assets/914d51a6-5a6e-4359-ac6b-833127ba51e5)
I would appreciate if you can report back after making those changes, thanks!

**Comment by assyrianic** [comment]
> Thanks for the feedback. This is likely a bug. You should however be able to remove the issue by untoggling `Boost After 2s`, `Hide Ad`, and setting `If Skip Available` to `Click button`. ![image](https://private-user-images.githubusercontent.com/25173236/361249217-914d51a6-5a6e-4359-ac6b-833127ba51e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2OTE5MDQsIm5iZiI6MTcyNDY5MTYwNCwicGF0aCI6Ii8yNTE3MzIzNi8zNjEyNDkyMTctOTE0ZDUxYTYtNWE2ZS00MzU5LWFjNmItODMzMTI3YmE1MWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDE3MDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyMDUwOWQ2NjJkZTJmYzFiOGIzMjEzODIwMDg2YzQ1MjU4ZjE1ZWU3ODk1ZGM0MGZiNTU2OGJjOWIyZDQxZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IlGqimzxo7nmbzp5E_4rBomE2tKfUVyzF6V3hkfw_18) I would appreciate if you can report back after making those changes, thanks!

how do I get to this menu?

**Comment by MartinBraquet** [comment]
Go to "extensions" in your toolbar (the piece of puzzle), then click on the add-on.
![image](https://github.com/user-attachments/assets/8f658541-82d9-4c74-82ef-744b3c970957)

**Comment by assyrianic** [comment]
> Go to "extensions" in your toolbar (the piece of puzzle), then click on the add-on. ![image](https://private-user-images.githubusercontent.com/25173236/361514362-8f658541-82d9-4c74-82ef-744b3c970957.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NjI2NDUsIm5iZiI6MTcyNDg2MjM0NSwicGF0aCI6Ii8yNTE3MzIzNi8zNjE1MTQzNjItOGY2NTg1NDEtODJkOS00Yzc0LTgyZWYtNzQ0YjNjOTcwOTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE2MjU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyOTU0MDZjMTUzZDg4ZGY2NjcxYTM1YTg4NjJlZDNlN2Q1YjMxYTIwN2U1ZmYxMDY1YTZmOWYyYWZmZDk3NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G3MnH5bp93Ue5y7XczQ-8sv5FHqBmvxzoUGiVTjwE-I)

I found it, these are the settings I'm using that fixes it!

![image](https://github.com/user-attachments/assets/a3427ecd-104e-4304-9acd-cac253757a02)

**Comment by MartinBraquet** [comment]
Awesome, thanks. I think it's an issue with how delayed boosting is implemented, but good to know that simply untoggling "Hide Ad" works. Closing the issue for now then.
