### ISSUE TITLE
Skip ads don't work

### ISSUE THREAD

**Issue by androidghosh** [MartinBraquet/youtube-adblock#18]
![image](https://github.com/user-attachments/assets/db8a6228-f580-420c-9f37-cb77dd89b281)
This function do not work. This addon successfully speeding up the ads but it isn't automatically clicking the skip button, I have to do it manually. Please fix it.

**Comment by MartinBraquet** [comment]
Isn't it a duplicate of #2 ?

**Comment by MartinBraquet** [comment]
Okay thanks. Then I'll close this issue and increase the priority of fixing #2 .
