### ISSUE TITLE
Doesn't work with YouTube Music

### ISSUE THREAD

**Issue by BluestoneDE** [MartinBraquet/youtube-adblock#4]
## Summary
The addon can't differentiate and marks all music as ads. This is a very specific use case only on [music.youtube.com].

## Reproduction
1. Go on [music.youtube.com]
2. Click on any music track

## Expected Behavior
The music plays and the ads are skipped.

## Actual Behavior
The music gets muted and sped up.

## Screenshots
![screenshot]

## Environment
 - OS: Windows 10
 - Firefox Version: 126.0.1
 - Addon Version: 1.58

[music.youtube.com]: https://music.youtube.com
[screenshot]: https://github.com/MartinBraquet/youtube-adblock/assets/65172029/200d5ec4-4f0d-4955-bb7c-18ce8b63c558

**Comment by MartinBraquet** [comment]
Thanks for the detailed description! I pushed a fix that should solve the issue in the current version 1.59. Let me know if that solves it for you as well.

**Comment by BluestoneDE** [comment]
Seems fixed. I can click on any music and only the ads are skipped. Great work!
