### ISSUE TITLE
Youtube now detects this

### ISSUE THREAD

**Issue by Archaeologistflash** [MartinBraquet/youtube-adblock#7]
Youtube now detects this blocker and stops the video, showing the 'using adblockers breaks Youtube's policies' message.
Refreshing the page allows the video to run until the next adbreak, and then it happens again. It was fine until a couple of days ago.
I'm using it in Firefox.

**Comment by MartinBraquet** [comment]
Thanks. One quick fix I see is to decrease the ad playback rate and keep the ad unmuted. Could you try to do so in the settings of your extension? I'd hope a playback rate around below 5 would work.

**Comment by Archaeologistflash** [comment]
I can't see any such setting. The only option I see for this extension is to block Youtube annotatons or not block them. There's nothing else showing under options for this extension.

**Comment by MartinBraquet** [comment]
Got it, two things:
- Could you make sure the extension is on the latest version? To do so, navigate to `about:addons`, click on the Youtube Adblock extension, it should show version 1.67. If not, click on the gear, then Check for updates.
![image](https://github.com/MartinBraquet/youtube-adblock/assets/25173236/379b98a1-db16-4ef1-bf2b-c78ed9b3dcb7)
- If it's on the latest version, you have access to difference settings that you can tweak, as shown below. To access it, click on the extensions symbol, then click on the Youtube Adblock extension. 
![image](https://github.com/MartinBraquet/youtube-adblock/assets/25173236/bc56f2c6-1e16-44ce-9840-af5410e9ab28)
![image](https://github.com/MartinBraquet/youtube-adblock/assets/25173236/370b7563-2c2c-42e0-90e8-164bc2272b20)
There you can disable Mute Ads, and set the playback rate to something lower like 5. This will tell the extension to make less modifications to ad, and hopefully youtube will be okay (or not notice) with it, and so it won't show the "using adblockers breaks Youtube's policies" message.

Let me know how it goes.

**Comment by Archaeologistflash** [comment]
Thanks, but it didn't work.
I updated it to that recent version (it was a much older version that I had), found the setting and set it to 4, and as soon as I ran a video, I got that 'violating Youtube's policies' message again. I've had to disable that add-on and install Youtube Ads Autoskip which is working so far.

________________________________

**Comment by BluestoneDE** [comment]
[I tired some things.](8)

**Comment by Archaeologistflash** [comment]
Now the other youtube ad skip extension has stopped working too. Youtube must be aware of them.
________________________________

**Comment by BluestoneDE** [comment]
Basically YouTube found out a way to detect other scripts that simulate the click on the "Skip Ad" button.
I found a temporary workaround and created a pull request.
Depending on the code review and maybe some changes from @MartinBraquet, this can be patched tonight.

**Comment by Archaeologistflash** [comment]
I'll cross fingers and toes. It's almost midnight here, though.  I'll try again in the morning if you have anything to test.
________________________________

**Comment by BluestoneDE** [comment]
If you really need it now, you can try my workaround:
1. [Download from my forked repository](https://github.com/BluestoneDE/youtube-adblock/archive/main.zip)
2. Move and unzip the file
3. Type `about:debugging` in the Firefox URL
4. Click on **"This Firefox"**
5. Right next to **Temporary Extensions** click on **"Load Temporary Add-on…"**
6. In the selection you can click on any file in the root directory of the unpacked extension

*I might need add these instructions to the installation section of the README.md*

**Comment by MartinBraquet** [comment]
Thanks @BluestoneDE , yes good idea to add to the readme those instructions for adding temporary extensions, such that users can try dev versions without setting a dev environment.

@Archaeologistflash We are working in #8 to release a new version that will hopefully solve your issue without breaking the behavior for all the other users.

**Comment by MartinBraquet** [comment]
@Archaeologistflash We finished the updates, could you follow the instructions at https://github.com/MartinBraquet/youtube-adblock/issues/7#issuecomment-2211495611 and let us know youtube stops flagging the page? The extension should work out of the box ideally (no need to modify the config in the extension popup). if that works, we'll merge the PR and release.

**Comment by Archaeologistflash** [comment]
Seems to work. The advert skips to the end. It doesn't click on skip, but I can do that. I did lose the image after one skip, but the others have worked ok.
Thanks.

**Comment by MartinBraquet** [comment]
Awesome, we just published a new version with the changes (1.70). Let us know if there is any further issue.

**Comment by Archaeologistflash** [comment]
Thanks. I've updated. Fingers crossed YT don't mess it up again any time soon.
________________________________

**Comment by BluestoneDE** [comment]
@MartinBraquet I did some more poking at the skip button.
I suspect that YouTube checks the `isTrusted` property. This is a read-only property.
[Read more about it here.](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted)

**Comment by MartinBraquet** [comment]
Thanks, for reference, this is now in #12
